package es.baste;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;

/**
 * Created by Fran on 31/07/2014.
 */
public class UtilesSonidos {

    private static List<Sound> sounds = new ArrayList<Sound>();

    public static List<Sound> getListaTodos() {
        return sounds;
    }

    public static void sonidos() {
        if (!sounds.isEmpty())
            return;

        sounds.add(new Sound("A mi me la suda", R.raw.a_mi_me_la_suda));
        sounds.add(new Sound("A mi no me vas a hacer ninguna pregunta", R.raw.a_mi_no_me_vas_a_hacer_ninguna_pregunta));
        sounds.add(new Sound("A tomar por culo, uno menos", R.raw.a_tomar_por_culo_uno_menos));
        sounds.add(new Sound("A tu casa", R.raw.a_tu_casa));
        sounds.add(new Sound("Adios", R.raw.adios));
        sounds.add(new Sound("Ah, sutil", R.raw.ah_sutil));
        sounds.add(new Sound("Ahora si", R.raw.ahora_si));
        sounds.add(new Sound("Ansioso", R.raw.ansioso));
        sounds.add(new Sound("Ay que miedo", R.raw.ay_que_miedo));
        sounds.add(new Sound("Ay, nos han Pillao", R.raw.ay_nos_han_pillao));
        sounds.add(new Sound("Bendiciones y buenas noches", R.raw.bendiciones_y_buenas_noches));
        sounds.add(new Sound("Bingo", R.raw.bingo));
        sounds.add(new Sound("Bombero con su manguera", R.raw.bombero_con_su_manguera));
        sounds.add(new Sound("Buen rollo", R.raw.buen_rollo));
        sounds.add(new Sound("Bueno, no pasa nada", R.raw.bueno_no_pasa_nada));
        sounds.add(new Sound("Bueno, un Whisky y a dormir", R.raw.bueno_un_whisky_y_a_dormir));
        sounds.add(new Sound("Bye Bye", R.raw.bye_bye));
        sounds.add(new Sound("Cabra Chillona", R.raw.cabra_chillona));
        sounds.add(new Sound("Cabra", R.raw.cabra));
        sounds.add(new Sound("Caramba, no me digas", R.raw.caramba_no_me_digas));
        sounds.add(new Sound("Cerveza, cerveza", R.raw.cerveza_cerveza));
        sounds.add(new Sound("Chico, que vas a hacer", R.raw.chico_que_vas_a_hacer));
        sounds.add(new Sound("Cobarde", R.raw.cobarde));
        sounds.add(new Sound("Como te de una miasca y la pechusques, la roscas", R.raw.como_te_de_una_miasca_y_la_pechusques_la_roscas));
        sounds.add(new Sound("Con el aire", R.raw.con_el_aire));
        sounds.add(new Sound("Correcto", R.raw.correcto));
        sounds.add(new Sound("Cállate Niña", R.raw.callate_nina));
        sounds.add(new Sound("Cállate", R.raw.callate));
        sounds.add(new Sound("De que te Ries tu", R.raw.de_que_te_ries_tu));
        sounds.add(new Sound("Dime hijo", R.raw.dime_hijo));
        sounds.add(new Sound("Donde está", R.raw.donde_esta));
        sounds.add(new Sound("El Conejo de la Loles", R.raw.el_conejo_de_la_loles));
        sounds.add(new Sound("EL MICROOOOOOO", R.raw.el_microoooooo));
        sounds.add(new Sound("Encantadas y cachondas", R.raw.encantadas_y_cachondas));
        sounds.add(new Sound("Es un escándalo", R.raw.es_un_escandalo));
        sounds.add(new Sound("Esto es mu verde", R.raw.esto_es_mu_verde));
        sounds.add(new Sound("Esto es un infierno Dios mío", R.raw.esto_es_un_infierno_dios_mio));
        sounds.add(new Sound("Esto se pone interesante", R.raw.esto_se_pone_interesante));
        sounds.add(new Sound("Estos catalanes son la leche", R.raw.estos_catalanes_son_la_leche));
        sounds.add(new Sound("Está muy rico", R.raw.esta_muy_rico));
        sounds.add(new Sound("Está muy salida", R.raw.esta_muy_salida));
        sounds.add(new Sound("Grito Wyoming", R.raw.grito_wyoming));
        sounds.add(new Sound("Guaguagua", R.raw.guaguagua));
        sounds.add(new Sound("Happy to be nene", R.raw.happy_to_be_nene));
        sounds.add(new Sound("Hasta luego lucas", R.raw.hasta_luego_lucas));
        sounds.add(new Sound("Hiuston, tenemos un problema", R.raw.hiuston_tenemos_un_problema));
        sounds.add(new Sound("Hola everyone", R.raw.hola_everyone));
        sounds.add(new Sound("Hola, que tal", R.raw.hola_que_tal));
        sounds.add(new Sound("Huele a caca", R.raw.huele_a_caca));
        sounds.add(new Sound("Iaiaiaia", R.raw.iaiaiaia));
        sounds.add(new Sound("Jajaja, hasta mañana", R.raw.jajaja_hasta_manana));
        sounds.add(new Sound("La abuela fuma, la abuela bebe", R.raw.la_abuela_fuma_la_abuela_bebe));
        sounds.add(new Sound("La ironia la has pillao, eh", R.raw.la_ironia_la_has_pillao_eh));
        sounds.add(new Sound("La madre que os parió", R.raw.la_madre_que_os_pario));
        sounds.add(new Sound("La Vamos a liar", R.raw.la_vamos_a_liar));
        sounds.add(new Sound("La Vida sigue igual", R.raw.la_vida_sigue_igual));
        sounds.add(new Sound("Las chicas son guarrillas", R.raw.las_chicas_son_guarrillas));
        sounds.add(new Sound("Luego, cuando salgamos, si quieres, nos damos un beso en la boca", R.raw.luego_cuando_salgamos_si_quieres_nos_damos_un_beso_en_la_boca));
        sounds.add(new Sound("Mala suerte", R.raw.mala_suerte));
        sounds.add(new Sound("Marrón", R.raw.marron));
        sounds.add(new Sound("Me cago en la leche", R.raw.me_cago_en_la_leche));
        sounds.add(new Sound("Me estas rayando ya neng", R.raw.me_estas_rayando_ya_neng));
        sounds.add(new Sound("Me ha hecho la casa así, BRUUUMP", R.raw.me_ha_hecho_la_casa_asi_bruuump));
        sounds.add(new Sound("Me pone", R.raw.me_pone));
        sounds.add(new Sound("Mear y no ehcar gota", R.raw.mear_y_no_ehcar_gota));
        sounds.add(new Sound("Mono con Dos Pistolas", R.raw.mono_con_dos_pistolas));
        sounds.add(new Sound("Muy Mal", R.raw.muy_mal));
        sounds.add(new Sound("Niño, que te pasa", R.raw.nino_que_te_pasa));
        sounds.add(new Sound("No he visto un tío como este en mi puta vida", R.raw.no_he_visto_un_tio_como_este_en_mi_puta_vida));
        sounds.add(new Sound("No lo sabia", R.raw.no_lo_sabia));
        sounds.add(new Sound("No me Digas", R.raw.no_me_digas));
        sounds.add(new Sound("No metabolizo el alcohol", R.raw.no_metabolizo_el_alcohol));
        sounds.add(new Sound("No sé quien es pero sé que le conozco", R.raw.no_se_quien_es_pero_se_que_le_conozco));
        sounds.add(new Sound("No te hagas el chulito, vale", R.raw.no_te_hagas_el_chulito_vale));
        sounds.add(new Sound("No, No, NOOOO", R.raw.no_no_noooo));
        sounds.add(new Sound("Nombre de Rajoy", R.raw.nombre_de_rajoy));
        sounds.add(new Sound("Oh, my god", R.raw.oh_my_god));
        sounds.add(new Sound("Ola k Ase", R.raw.ola_k_ase));
        sounds.add(new Sound("Otra vez", R.raw.otra_vez));
        sounds.add(new Sound("Speak English Very Good, Vamos", R.raw.peak_english_very_good_vamos));
        sounds.add(new Sound("Pelame la banana", R.raw.pelame_la_banana));
        sounds.add(new Sound("Pero mujer, que haces", R.raw.pero_mujer_que_haces));
        sounds.add(new Sound("Pero, que estás diciendo tu", R.raw.pero_que_estas_diciendo_tu));
        sounds.add(new Sound("Pesada", R.raw.pesada));
        sounds.add(new Sound("Pillín", R.raw.pillin));
        sounds.add(new Sound("Poneros a trabajar de una vez, hombre", R.raw.poneros_a_trabajar_de_una_vez_hombre));
        sounds.add(new Sound("Por qué no te callas y cierras la boca", R.raw.por_que_no_te_callas_y_cierras_la_boca));
        sounds.add(new Sound("Profesional, muy Profesional", R.raw.profesional_muy_profesional));
        sounds.add(new Sound("Puñalada trapera, patada en los huevos y rencor", R.raw.punalada_trapera_patada_en_los_huevos_y_rencor));
        sounds.add(new Sound("Que arte y que podreío hijo de tu madre", R.raw.que_arte_y_que_podreio_hijo_de_tu_madre));
        sounds.add(new Sound("Que asco", R.raw.que_asco));
        sounds.add(new Sound("Que guay, como mola", R.raw.que_guay_como_mola));
        sounds.add(new Sound("Que haces tu", R.raw.que_haces_tu));
        sounds.add(new Sound("Que me dices", R.raw.que_me_dices));
        sounds.add(new Sound("Que me estás container", R.raw.que_me_estas_container));
        sounds.add(new Sound("Que no pare la fiesta", R.raw.que_no_pare_la_fiesta));
        sounds.add(new Sound("Que no te enteras", R.raw.que_no_te_enteras));
        sounds.add(new Sound("Que pasa", R.raw.que_pasa));
        sounds.add(new Sound("Que se cae", R.raw.que_se_cae));
        sounds.add(new Sound("Que se mea", R.raw.que_se_mea));
        sounds.add(new Sound("Que te pasa", R.raw.que_te_pasa));
        sounds.add(new Sound("Que te pasó, no se cuantos, esto, lo otro", R.raw.que_te_paso_no_se_cuantos_esto_lo_otro));
        sounds.add(new Sound("Queremos botellona", R.raw.queremos_botellona));
        sounds.add(new Sound("Quien es el eco", R.raw.quien_es_el_eco));
        sounds.add(new Sound("Quien sabe", R.raw.quien_sabe));
        sounds.add(new Sound("Quítate de ahí", R.raw.quitate_de_ahi));
        sounds.add(new Sound("Rebota, rebota y en tu culo explota", R.raw.rebota_rebota_y_en_tu_culo_explota));
        sounds.add(new Sound("Relaxing cup of cafe con leche", R.raw.relaxing_cup_of_cafe_con_leche));
        sounds.add(new Sound("Respóndeme bien respondio", R.raw.respondeme_bien_respondio));
        sounds.add(new Sound("Risa abuela", R.raw.risa_abuela));
        sounds.add(new Sound("Risa vergonzosa", R.raw.risa_vergonzosa));
        sounds.add(new Sound("Risa", R.raw.risa));
        sounds.add(new Sound("Seguro", R.raw.seguro));
        sounds.add(new Sound("Sentí asco, sentí rabia, no sé lo que sentí", R.raw.senti_asco_senti_rabia_no_se_lo_que_senti));
        sounds.add(new Sound("Señor, te piedad", R.raw.senor_te_piedad));
        sounds.add(new Sound("Si bebes no conduzcas", R.raw.si_bebes_no_conduzcas));
        sounds.add(new Sound("Si se puede", R.raw.si_se_puede));
        sounds.add(new Sound("Si tengo algo, se lo estampo en la cabeza y lo mato", R.raw.si_tengo_algo_se_lo_estampo_en_la_cabeza_y_lo_mato));
        sounds.add(new Sound("Tato", R.raw.tato));
        sounds.add(new Sound("Te doy dos ostias o que pasa", R.raw.te_doy_dos_ostias_o_que_pasa));
        sounds.add(new Sound("Te duele", R.raw.te_duele));
        sounds.add(new Sound("Te veo, te veo y me mareo", R.raw.te_veo_te_veo_y_me_mareo));
        sounds.add(new Sound("Tiene un Problema", R.raw.tiene_un_problema));
        sounds.add(new Sound("Tigre Ellaculator", R.raw.tigre_ellaculator));
        sounds.add(new Sound("Todo de cachondeo", R.raw.todo_de_cachondeo));
        sounds.add(new Sound("Toma liada", R.raw.toma_liada));
        sounds.add(new Sound("Trampa sin Escapatoria", R.raw.trampa_sin_escapatoria));
        sounds.add(new Sound("Tu crees, lo dudo", R.raw.tu_crees_lo_dudo));
        sounds.add(new Sound("Tu eres muy malo", R.raw.tu_eres_muy_malo));
        sounds.add(new Sound("Tu vas a llegar muy lejos", R.raw.tu_vas_a_llegar_muy_lejos));
        sounds.add(new Sound("Te has hecho daño, Lucy", R.raw.te_has_hecho_dano_lucy));
        sounds.add(new Sound("Un Beso", R.raw.un_beso));
        sounds.add(new Sound("Una mala tarde la tiene cualquiera", R.raw.una_mala_tarde_la_tiene_cualquiera));
        sounds.add(new Sound("Una mierda", R.raw.una_mierda));
        sounds.add(new Sound("Uyyy, madre", R.raw.uyyy_madre));
        sounds.add(new Sound("Va como un pepino", R.raw.va_como_un_pepino));
        sounds.add(new Sound("Vale, me alegro mucho", R.raw.vale_me_alegro_mucho));
        sounds.add(new Sound("Vaya lio, que follón", R.raw.vaya_lio_que_follon));
        sounds.add(new Sound("Vergüenza ajena", R.raw.verguenza_ajena));
        sounds.add(new Sound("Whatsapp, no", R.raw.whatsapp_no));
        sounds.add(new Sound("Y punto y se ha acabao", R.raw.y_punto_y_se_ha_acabao));
        sounds.add(new Sound("Y yo también", R.raw.y_yo_tambien));
        sounds.add(new Sound("Yo con sujetador, perderé mucho, pero tu con casco tienes que ganar un montón", R.raw.yo_con_sujetador_perdere_mucho_pero_tu_con_casco_tienes_que_ganar_un_monton));
        sounds.add(new Sound("Yo no se como no me han dado los ataques pelépticos que me dan", R.raw.yo_no_se_como_no_me_han_dado_los_ataques_pelepticos_que_me_dan));
        sounds.add(new Sound("Zas, en toda la boca", R.raw.zas_en_toda_la_boca));
        sounds.add(new Sound("Zasca", R.raw.zasca));
        sounds.add(new Sound("¿Que pesa más, un kilo de hierro o de paja?", R.raw.que_pesa_mas_un_kilo_de_hierro_o_de_paja));
        sounds.add(new Sound("Últimos 10 minutos", R.raw.ultimos_10_minutos));

        //1.1
        sounds.add(new Sound("Al final se casan", R.raw.al_final_se_casan));
        sounds.add(new Sound("Callaros, coño", R.raw.callaros_cono));
        sounds.add(new Sound("IMPOSIBLE", R.raw.imposible));
        sounds.add(new Sound("La película más mala", R.raw.la_pelicula_mas_mala));
        sounds.add(new Sound("Mi Aplauso", R.raw.mi_aplauso));
        sounds.add(new Sound("No se muera", R.raw.no_se_muera));
        sounds.add(new Sound("Pa chulo yo", R.raw.pa_chulo_yo));
        sounds.add(new Sound("Que Bien, que Guay", R.raw.que_bien_que_guay));
        sounds.add(new Sound("Que lico", R.raw.que_lico));
        sounds.add(new Sound("Que m'atraganto", R.raw.que_me_atraganto));
        sounds.add(new Sound("Unas cañas en Nazaret", R.raw.unas_canas_en_nazaret));
        sounds.add(new Sound("Vicio sexual", R.raw.vicio_sexual));
        sounds.add(new Sound("What's your name, please", R.raw.whats_your_name_please));
        sounds.add(new Sound("Ñaca Ñaca", R.raw.naca_naca));

        //1.2
        sounds.add(new Sound("Adios, que me voy para la otra vida", R.raw.adios_que_me_voy_para_la_otra_vida));
        sounds.add(new Sound("Adios-Bush", R.raw.adios_bush));
        sounds.add(new Sound("Animales y personas necesitamos sexo todas las horas", R.raw.animales_y_personas_necesitamos_sexo_todas_las_horas));
        sounds.add(new Sound("Arriba, venga", R.raw.arriba_venga));
        sounds.add(new Sound("Cansino", R.raw.cansino));
        sounds.add(new Sound("Como Tarzán por la selva", R.raw.como_tarzan_por_la_selva));
        sounds.add(new Sound("Coño, toma castaña", R.raw.cono_toma_castana));
        sounds.add(new Sound("El coche fantástico y un vater", R.raw.el_coche_fantastico_y_un_vater));
        sounds.add(new Sound("Es que es ricídulo, Joder", R.raw.es_que_es_ricidulo_joder));
        sounds.add(new Sound("Escribir un libro, plantar un árbol y...", R.raw.escribir_un_libro_plantar_un_arbol_y));
        sounds.add(new Sound("Ese és un bocazas", R.raw.ese_es_un_bocazas));
        sounds.add(new Sound("Hasta la vista, baby", R.raw.hasta_la_vista_baby));
        sounds.add(new Sound("Hay que ser tonto pa hacerlo", R.raw.hay_que_ser_tonto_pa_hacerlo));
        sounds.add(new Sound("Hija, disimula un poco, nena, que se te ve el plumón", R.raw.hija_disimula_un_poco_nena_que_se_te_ve_el_plumon));
        sounds.add(new Sound("Huevo en el microondas", R.raw.huevo_en_el_microondas));
        sounds.add(new Sound("Jódete", R.raw.jodete));
        sounds.add(new Sound("La he liado parda", R.raw.la_he_liado_parda));
        sounds.add(new Sound("La señora que más grita de España", R.raw.la_senora_que_mas_grita_de_espana));
        sounds.add(new Sound("Madre mía, Anna, que nervios tengo", R.raw.madre_mia_anna_que_nervios_tengo));
        sounds.add(new Sound("Manipuladores", R.raw.manipuladores));
        sounds.add(new Sound("Me cago en tus muelas españolas", R.raw.me_cago_en_tus_muelas_espanolas));
        sounds.add(new Sound("No hay más que jaleo, peleas, puñaladas y de tó", R.raw.no_hay_mas_que_jaleo_peleas_punaladas_y_de_to));
        sounds.add(new Sound("No puedes fumarte un porro y meterte el clase porqué no te vas a enterar de nada", R.raw.no_puedes_fumarte_un_porro_y_meterte_el_clase_porque_no_te_vas_a_enterar_de_nada));
        sounds.add(new Sound("No te rias, que es peor", R.raw.no_te_rias_que_es_peor));
        sounds.add(new Sound("Olé", R.raw.ole));
        sounds.add(new Sound("Ostia", R.raw.ostia));
        sounds.add(new Sound("Pero que listo es mi niño", R.raw.pero_que_listo_es_mi_nino));
        sounds.add(new Sound("Político en inglés", R.raw.politico_en_ingles));
        sounds.add(new Sound("Por qué, señor, por qué", R.raw.por_que_senor_por_que));
        sounds.add(new Sound("Que loco estoy", R.raw.que_loco_estoy));
        sounds.add(new Sound("Que mala leche hay en este programa", R.raw.que_mala_leche_hay_en_este_programa));
        sounds.add(new Sound("Que mente más sucia tienes", R.raw.que_mente_mas_sucia_tienes));
        sounds.add(new Sound("Que pedrà", R.raw.que_pedra));
        sounds.add(new Sound("Que poco cochina eres", R.raw.que_poco_cochina_eres));
        sounds.add(new Sound("Que risa, tia felisa", R.raw.que_risa_tia_felisa));
        sounds.add(new Sound("Quítate de ahí, que está la cámara", R.raw.quitate_de_ahi_que_esta_la_camara));
        sounds.add(new Sound("Rico, rico, de lo bueno lo mejor, de los mejor lo superior", R.raw.rico_rico_de_lo_bueno_lo_mejor_de_los_mejor_lo_superior));
        sounds.add(new Sound("Si te caes te pego", R.raw.si_te_caes_te_pego));
        sounds.add(new Sound("Tiene los huevos así de grandes", R.raw.tiene_los_huevos_asi_de_grandes));
        sounds.add(new Sound("Tienes 12 Tíos", R.raw.tienes_12_tios));
        sounds.add(new Sound("Toma moreno", R.raw.toma_moreno));
        sounds.add(new Sound("UN TERREMOTOOOOO", R.raw.un_terremotooooo));
        sounds.add(new Sound("Urgencias", R.raw.urgencias));
        sounds.add(new Sound("Vamos, esto ya tiene guasa", R.raw.vamos_esto_ya_tiene_guasa));
        sounds.add(new Sound("Vete a casa, porqué estás batiendo todas las marcas de la inutilidad", R.raw.vete_a_casa_porque_estas_batiendo_todas_las_marcas_de_la_inutilidad));
        sounds.add(new Sound("Viva el ejército", R.raw.viva_el_ejercito));
        sounds.add(new Sound("Volaré", R.raw.volare));
        sounds.add(new Sound("Ya me puedo morir tranquilamente", R.raw.ya_me_puedo_morir_tranquilamente));
        sounds.add(new Sound("¿Como se llama el presidente este negro...?", R.raw.como_se_llama_el_presidente_este_negro));
        sounds.add(new Sound("¿Cuando empieza y termina la guerra civil española?", R.raw.cuando_empieza_y_termina_la_guerra_civil_espanola));
        sounds.add(new Sound("¿Cuantos años tiene usted, Paula?", R.raw.cuantos_anos_tiene_usted_paula));
        sounds.add(new Sound("¿De donde han sacado estas horchatas?", R.raw.de_donde_han_sacado_estas_horchatas));
        sounds.add(new Sound("¿Por qué no te callas?", R.raw.por_que_no_te_callas));
        sounds.add(new Sound("Es usted Marisol", R.raw.es_usted_marisol));

        //1.3
        sounds.add(new Sound("A la mierda ya", R.raw.a_la_mierda_ya));
        sounds.add(new Sound("Ah, ah vale", R.raw.ah_ah_vale));
        sounds.add(new Sound("Al ataque", R.raw.al_ataque));
        sounds.add(new Sound("Aleluya", R.raw.aleluya));
        sounds.add(new Sound("Anda mi madre, pues yo no sabía eso", R.raw.anda_mi_madre_pues_yo_no_sabia_eso));
        sounds.add(new Sound("Anda", R.raw.anda));
        sounds.add(new Sound("Antonio, que no te enteras de nada", R.raw.antonio_que_no_te_enteras_de_nada));
        sounds.add(new Sound("Atención al pajarito", R.raw.atencion_al_pajarito));
        sounds.add(new Sound("Ay que pena, pobrecito", R.raw.ay_que_pena_pobrecito));
        sounds.add(new Sound("Ay, que me parto", R.raw.ay_que_me_parto));
        sounds.add(new Sound("Bravo bravo bravo", R.raw.bravo_bravo_bravo));
        sounds.add(new Sound("Bueno, adios cariño, te quiero, un beso fuerte, adios, ya está", R.raw.bueno_adios_carino_te_quiero_un_beso_fuerte_adios_ya_esta));
        sounds.add(new Sound("Casi", R.raw.casi));
        sounds.add(new Sound("Claro", R.raw.claro));
        sounds.add(new Sound("Con Franco esto no pasaba", R.raw.con_franco_esto_no_pasaba));
        sounds.add(new Sound("Cuanto talento desperdiciado hay por ahí", R.raw.cuanto_talento_desperdiciado_hay_por_ahi));
        sounds.add(new Sound("Dale, dale, dale", R.raw.dale_dale_dale));
        sounds.add(new Sound("Déjame hablar", R.raw.dejame_hablar));
        sounds.add(new Sound("El amor es lo más bonito del mundo", R.raw.el_amor_es_lo_mas_bonito_del_mundo));
        sounds.add(new Sound("El que haya dao permiso pa hacer esto, que de la cara", R.raw.el_que_haya_dao_permiso_pa_hacer_esto_que_de_la_cara));
        sounds.add(new Sound("En to la boca", R.raw.en_to_la_boca));
        sounds.add(new Sound("Es algo muy fuerte", R.raw.es_algo_muy_fuerte));
        sounds.add(new Sound("Es que hace un mes que no zumbo", R.raw.es_que_hace_un_mes_que_no_zumbo));
        sounds.add(new Sound("Eso está mu feo", R.raw.eso_esta_mu_feo));
        sounds.add(new Sound("Estado civil", R.raw.estado_civil));
        sounds.add(new Sound("Este tio es un campeón", R.raw.este_tio_es_un_campeon));
        sounds.add(new Sound("Estuve esperando hasta que se me incharon los huevos, vine y lo hice", R.raw.estuve_esperando_hasta_que_se_me_incharon_los_huevos_vine_y_lo_hice));
        sounds.add(new Sound("Fantasma", R.raw.fantasma));
        sounds.add(new Sound("Felicidades de corazón", R.raw.felicidades_de_corazon));
        sounds.add(new Sound("Frenar, párate, stop", R.raw.frenar_parate_stop));
        sounds.add(new Sound("Fuera de aquí", R.raw.fuera_de_aqui));
        sounds.add(new Sound("Gangnam Style", R.raw.gangnam_style));
        sounds.add(new Sound("Hasta mañana, hasta luego", R.raw.hasta_manana_hasta_luego));
        sounds.add(new Sound("Hazte un favor, guarad esas pastillas", R.raw.hazte_un_favor_guarad_esas_pastillas));
        sounds.add(new Sound("Hemos pasado un miedo que no te puedes imaginar", R.raw.hemos_pasado_un_miedo_que_no_te_puedes_imaginar));
        sounds.add(new Sound("Hombre llorando", R.raw.hombre_llorando));
        sounds.add(new Sound("Joder, que friki eres", R.raw.joder_que_friki_eres));
        sounds.add(new Sound("La coherencia escasea tanto en la política española como los libros en Gandía Shore", R.raw.la_coherencia_escasea_tanto_en_la_politica_espanola_como_los_libros_en_gandia_shore));
        sounds.add(new Sound("La Nancy O", R.raw.la_nancy_o));
        sounds.add(new Sound("La película esa ya la he visto, y al final siempre pone fin", R.raw.la_pelicula_esa_ya_la_he_visto_y_al_final_siempre_pone_fin));
        sounds.add(new Sound("La pregunta mamporrera", R.raw.la_pregunta_mamporrera));
        sounds.add(new Sound("Los jóvenes no leen porqué están con el internet", R.raw.los_jovenes_no_leen_porque_estan_con_el_internet));
        sounds.add(new Sound("Machista", R.raw.machista));
        sounds.add(new Sound("Marranote", R.raw.marranote));
        sounds.add(new Sound("Me cachis en Bruce Lee", R.raw.me_cachis_en_bruce_lee));
        sounds.add(new Sound("Me cago en diez, ahora me he cagao", R.raw.me_cago_en_diez_ahora_me_he_cagao));
        sounds.add(new Sound("Me canso de la postura del minero", R.raw.me_canso_de_la_postura_del_minero));
        sounds.add(new Sound("Me encanta", R.raw.me_encanta));
        sounds.add(new Sound("Me he meao de la alegria", R.raw.me_he_meao_de_la_alegria));
        sounds.add(new Sound("Me importa tres narices", R.raw.me_importa_tres_narices));
        sounds.add(new Sound("Me lo comería todo", R.raw.me_lo_comeria_todo));
        sounds.add(new Sound("Mente de mono", R.raw.mente_de_mono));
        sounds.add(new Sound("Menudos guionistas", R.raw.menudos_guionistas));
        sounds.add(new Sound("Mira la tijera", R.raw.mira_la_tijera));
        sounds.add(new Sound("Mucho miedo", R.raw.mucho_miedo));
        sounds.add(new Sound("Me han engañao", R.raw.me_han_enganao));
        sounds.add(new Sound("Más claro chorizo pamplona", R.raw.mas_claro_chorizo_pamplona));
        sounds.add(new Sound("Niño sorprendido", R.raw.nino_sorprendido));
        sounds.add(new Sound("No lloré porqué me daba vergüenza", R.raw.no_llore_porque_me_daba_verguenza));
        sounds.add(new Sound("No, otra vez no", R.raw.no_otra_vez_no));
        sounds.add(new Sound("Oatia, este tio ha estudio", R.raw.oatia_este_tio_ha_estudio));
        sounds.add(new Sound("Oh my goooooood", R.raw.oh_my_goooooood));
        sounds.add(new Sound("Ole los cojones", R.raw.ole_los_cojones));
        sounds.add(new Sound("Ole sus cataplines, así de claro", R.raw.ole_sus_cataplines_asi_de_claro));
        sounds.add(new Sound("Ole tu", R.raw.ole_tu));
        sounds.add(new Sound("Por el amor de Dios, solo pido ayuda", R.raw.por_el_amor_de_dios_solo_pido_ayuda));
        sounds.add(new Sound("Por favor, por favor", R.raw.por_favor_por_favor));
        sounds.add(new Sound("Por los coches rápidos y las tetas gordas", R.raw.por_los_coches_rapidos_y_las_tetas_gordas));
        sounds.add(new Sound("Pues jódete", R.raw.pues_jodete));
        sounds.add(new Sound("Que fuerte, se caga la perra", R.raw.que_fuerte_se_caga_la_perra));
        sounds.add(new Sound("Que lo sepa todo el mundo que es mentira", R.raw.que_lo_sepa_todo_el_mundo_que_es_mentira));
        sounds.add(new Sound("Que lástima", R.raw.que_lastima));
        sounds.add(new Sound("Que manera de hablar, que gusto", R.raw.que_manera_de_hablar_que_gusto));
        sounds.add(new Sound("Que me caso", R.raw.que_me_caso));
        sounds.add(new Sound("Que muerte más mala", R.raw.que_muerte_mas_mala));
        sounds.add(new Sound("Que nos cogen", R.raw.que_nos_cogen));
        sounds.add(new Sound("Quiero que se peleen", R.raw.quiero_que_se_peleen));
        sounds.add(new Sound("Risa burlona", R.raw.risa_burlona));
        sounds.add(new Sound("Sigue siendo aquel", R.raw.sigue_siendo_aquel));
        sounds.add(new Sound("Soy cinturón negro karateka", R.raw.soy_cinturon_negro_karateka));
        sounds.add(new Sound("Teatro y del bueno", R.raw.teatro_y_del_bueno));
        sounds.add(new Sound("Tiene mucho cuento chino, de verdad", R.raw.tiene_mucho_cuento_chino_de_verdad));
        sounds.add(new Sound("Tienen que llevarlo al psiquiatra", R.raw.tienen_que_llevarlo_al_psiquiatra));
        sounds.add(new Sound("Tierra trágame", R.raw.tierra_tragame));
        sounds.add(new Sound("Todo el mundo pierde la memoria para las cosas que no le interesan", R.raw.todo_el_mundo_pierde_la_memoria_para_las_cosas_que_no_le_interesan));
        sounds.add(new Sound("Toma escopeta, CORRE", R.raw.toma_escopeta_corre));
        sounds.add(new Sound("TOMAAA", R.raw.tomaaa));
        sounds.add(new Sound("Una fiesta de la leche, vamos", R.raw.una_fiesta_de_la_leche_vamos));
        sounds.add(new Sound("Vale", R.raw.vale));
        sounds.add(new Sound("Vaya mal rollito", R.raw.vaya_mal_rollito));
        sounds.add(new Sound("Vaya un personaje", R.raw.vaya_un_personaje));
        sounds.add(new Sound("Venga bonita, venga", R.raw.venga_bonita_venga));
        sounds.add(new Sound("Venga, gracias bonita", R.raw.venga_gracias_bonita));
        sounds.add(new Sound("Viva el semen español", R.raw.viva_el_semen_espanol));
        sounds.add(new Sound("Y a ver como compite usted con los chinos", R.raw.y_a_ver_como_compite_usted_con_los_chinos));
        sounds.add(new Sound("Yo es que soy abstemia", R.raw.yo_es_que_soy_abstemia));
        sounds.add(new Sound("Yo estoy preparado para ser un superhombre de esos", R.raw.yo_estoy_preparado_para_ser_un_superhombre_de_esos));
        sounds.add(new Sound("Yo lo noto un poco raro, no me lo creo del todo", R.raw.yo_lo_noto_un_poco_raro_no_me_lo_creo_del_todo));
        sounds.add(new Sound("Yo no soy chulo, soy claro", R.raw.yo_no_soy_chulo_soy_claro));
        sounds.add(new Sound("¿Con qué nervio del cuerpo humano es con el que mejor te lo pasas?", R.raw.con_que_nervio_del_cuerpo_humano_es_con_el_que_mejor_te_lo_pasas));
        sounds.add(new Sound("¿Cuanto es 1x1?", R.raw.cuanto_es_1x1));
        sounds.add(new Sound("¿Donde está la pelotita?", R.raw.donde_esta_la_pelotita));
        sounds.add(new Sound("¿Han visto que contencto está?", R.raw.han_visto_que_contencto_esta));
        sounds.add(new Sound("¿Pero este cabrón quien es?", R.raw.pero_este_cabron_quien_es));
        sounds.add(new Sound("¿Por qué no nos ejecutáis y acabamos con esto?", R.raw.por_que_no_nos_ejecutais_y_acabamos_con_esto));
        sounds.add(new Sound("¿Por qué toses tanto?", R.raw.por_que_toses_tanto));
        sounds.add(new Sound("¿Que tal, mi amor?", R.raw.que_tal_mi_amor));
        sounds.add(new Sound("¿Que te pasa, muchacho?", R.raw.que_te_pasa_muchacho));
        sounds.add(new Sound("¿Queréis intentarlo otra vez?", R.raw.quereis_intentarlo_otra_vez));
        sounds.add(new Sound("¿Te crees muy listo?", R.raw.te_crees_muy_listo));
        sounds.add(new Sound("¿Y este tío que hace aquí?", R.raw.y_este_tio_que_hace_aqui));

        //1.4
        sounds.add(new Sound("A cantar, a cantar y a beber", R.raw.a_cantar_a_cantar_y_a_beber));
        sounds.add(new Sound("Agárrense los machos", R.raw.agarrense_los_machos));
        sounds.add(new Sound("Asín de claro", R.raw.asin_de_claro));
        sounds.add(new Sound("Como yo", R.raw.como_yo));
        sounds.add(new Sound("Con la crisi, esto es demasiao, lo primero esta en comer", R.raw.con_la_crisi_esto_es_demasiao_lo_primero_esta_en_comer));
        sounds.add(new Sound("Dios mío, Dios está y Dios es grande", R.raw.dios_mio_dios_esta_y_dios_es_grande));
        sounds.add(new Sound("Dios mío, que horror", R.raw.dios_mio_qie_horror));
        sounds.add(new Sound("Droga mala", R.raw.droga_mala));
        sounds.add(new Sound("Efectivamente, subidón total", R.raw.efectivamente_subidon_total));
        sounds.add(new Sound("El mundo lo mueven dos cosas, el dinero y el sexo", R.raw.el_mundo_lo_mueven_dos_cosas_el_dinero_y_el_sexo));
        sounds.add(new Sound("Ella se queda con hambre", R.raw.ella_se_queda_con_hambre));
        sounds.add(new Sound("Equilicua", R.raw.equilicua));
        sounds.add(new Sound("Eso es cierto cierto", R.raw.eso_es_cierto_cierto));
        sounds.add(new Sound("España va bien", R.raw.espana_va_bien));
        sounds.add(new Sound("GUAPO", R.raw.guapo));
        sounds.add(new Sound("Hay, que me hago pipi", R.raw.hay_que_me_hago_pipi));
        sounds.add(new Sound("Lávate la boca con jabón ya, hombre", R.raw.lavate_la_boca_con_jabon_ya_hombre));
        sounds.add(new Sound("Me da mucha rabia", R.raw.me_da_mucha_rabia));
        sounds.add(new Sound("Me gusta tu pelo y tu acento", R.raw.me_gusta_tu_pelo_y_tu_acento));
        sounds.add(new Sound("Me la pela", R.raw.me_la_pela));
        sounds.add(new Sound("Mu bien, si que es verdad, un aplauso pa usted", R.raw.mu_bien_si_que_es_verdad_un_aplauso_pa_usted));
        sounds.add(new Sound("Muy bonito, si señor", R.raw.muy_bonito_si_senor));
        sounds.add(new Sound("No es que nos tomen por idiota, yo empiezo a pensar que soy idiota", R.raw.no_es_que_nos_tomen_por_idiota_yo_empiezo_a_pensar_que_soy_idiota));
        sounds.add(new Sound("No estoy preparado, señor", R.raw.no_estoy_preparado_senor));
        sounds.add(new Sound("No hay derecho, ¿quién manda aqui?. El rico podrido", R.raw.no_hay_derecho_quien_manda_aqui_el_rico_podrido));
        sounds.add(new Sound("No puede ser", R.raw.no_puede_ser));
        sounds.add(new Sound("No tendría que haberte visto, hoy voy a tener pesadillas", R.raw.no_tendria_que_haberte_visto_hoy_voy_a_tener_pesadillas));
        sounds.add(new Sound("Nunca se le ha subido los humos a la cabeza, como decimos vulgarmente", R.raw.nunca_se_le_ha_subido_los_humos_a_la_cabeza_como_decimos_vulgarmente));
        sounds.add(new Sound("Ole, que bonito eres", R.raw.ole_que_bonito_eres));
        sounds.add(new Sound("Que fuerte, que fuerte", R.raw.que_fuerte_que_fuerte));
        sounds.add(new Sound("Quita esto", R.raw.quita_esto));
        sounds.add(new Sound("Si, bueno, es posible", R.raw.si_bueno_es_posible));
        sounds.add(new Sound("Son ladrones, criminales, canallas", R.raw.son_ladrones_criminales_canallas));
        sounds.add(new Sound("SUBIDÓN", R.raw.subidon));
        sounds.add(new Sound("Toma tomate", R.raw.toma_tomate));
        sounds.add(new Sound("Venga, déjalo y vamos a empezar otra vez", R.raw.venga_dejalo_y_vamos_a_empezar_otra_vez));
        sounds.add(new Sound("¿Que has dicho?", R.raw.que_has_dicho));
        sounds.add(new Sound("¿Qué haces?", R.raw.que_haces));
        sounds.add(new Sound("¿Y esto que es?", R.raw.y_esto_que_es));

        //1.5
        sounds.add(new Sound("A lo que va es a ponerse cachondo", R.raw.a_lo_que_va_es_a_ponerse_cachondo, true));
        sounds.add(new Sound("Adios 2", R.raw.adios_2, true));
        sounds.add(new Sound("Cateto a babor", R.raw.cateto_a_babor, true));
        sounds.add(new Sound("Cuenta por esa boca", R.raw.cuenta_por_esa_boca, true));
        sounds.add(new Sound("Cuidao conmigo que soy karateka", R.raw.cuidao_conmigo_que_soy_karateka, true));
        sounds.add(new Sound("Esas cabezas no están bien", R.raw.esas_cabezas_no_estan_bien, true));
        sounds.add(new Sound("Joer, ¿que ha pasao aquí?", R.raw.joer_que_ha_pasao_aqui, true));
        sounds.add(new Sound("Lo teneis crudo", R.raw.lo_teneis_crudo, true));
        sounds.add(new Sound("Loco, párate", R.raw.loco_parate, true));
        sounds.add(new Sound("Mátenme", R.raw.matenme, true));
        sounds.add(new Sound("Niquelao...Chapó", R.raw.niquelao_chapo, true));
        sounds.add(new Sound("No siento las piernas", R.raw.no_siento_las_piernas, true));
        sounds.add(new Sound("No tengo vergüenza", R.raw.no_tengo_verguenza, true));
        sounds.add(new Sound("Que alegria, que bien", R.raw.que_alegria_que_bien, true));
        sounds.add(new Sound("QUEREMOS VER VIOLENCIA", R.raw.queremos_ver_violencia, true));
        sounds.add(new Sound("Raro, raro, raro", R.raw.raro_raro_raro, true));
        sounds.add(new Sound("Resignación y paciencia", R.raw.resignacion_y_paciencia, true));
        sounds.add(new Sound("Risa de rata", R.raw.risa_de_rata, true));
        sounds.add(new Sound("Se podría haber preparao una catástrofe de miedo", R.raw.se_podria_haber_preparao_una_catastrofe_de_miedo, true));
        sounds.add(new Sound("Si la han cagao, que lo arreglen", R.raw.si_la_han_cagao_que_lo_arreglen, true));
        sounds.add(new Sound("Si no bebieran, se irían a rezar el rosario, comprenderías que no les pasa nada", R.raw.si_no_bebieran_se_irian_a_rezar_el_rosario_comprenderias_que_no_les_pasa_nada, true));
        sounds.add(new Sound("Top Tripi", R.raw.top_tripi, true));
        sounds.add(new Sound("Va de listo", R.raw.va_de_listo, true));
        sounds.add(new Sound("What a fuck.", R.raw.what_a_fuck, true));
        sounds.add(new Sound("Y eso duele", R.raw.y_eso_duele, true));
        sounds.add(new Sound("¿Como t'has quedao?", R.raw.como_te_has_quedao, true));
        sounds.add(new Sound("¿Eso quien se lo cree?. Yo no", R.raw.eso_quien_se_lo_cree_yo_no, true));
        sounds.add(new Sound("¿Todo bien?. ¿Todo correcto?, Y yo que me alegro, hombre", R.raw.todo_bien_todo_correcto_y_yo_que_me_alegro_hombre, true));



        Collections.sort(sounds, new Comparator<Sound>() {
            public int compare(Sound s1, Sound s2) {
                return s1.getNombre().compareTo(s2.getNombre());
            }
        });
    }
}
